### ISSUE TITLE
Utilize `pybids` sqlite database

### ISSUE THREAD

**Issue by pvandyken** [akhanf/snakebids#123]
So long as we're starting a family of `snakebids ...` CLI command, it would be great to have a command that saves your dataset structure as a pybids sqlite database. The command could be maybe `snakebids cache [bids_path]`, and that would create or update the database at some folder (e.g. `.snakebids-cache`) relative to the `bids_path`. `snakebids cache [bids_path] -d` would delete any database at that site. Then, whenever `generate_inputs()` is called, if it finds the appropriate database path, it will use that rather than re-indexing the entire dataset.

Obviously, the catch to this is that you'd have to manually refresh the cache every time the dataset updated. But it would be a strictly opt-in feature, so we could assume that anyone using it would know that.

**Comment by pvandyken** [comment]
Also, obviously `pybids` already has a CLI command that more or less does what I described. The advantage of making our own is that we can control the database path, making it interoperable with `generate_inputs()`

**Comment by kaitj** [comment]
I haven't tried to use this `pybids` feature too much as they implemented it in a later version than what I had started with. Unless I am mistaken, they have a `save` method that allows the db to be saved to a user-defined path

Overall, I do agree this would be a helpful implementation and will likely speed up future workflows.

**Comment by kaitj** [comment]
Some comments from todays dev lunch - please correct / update if I missed anything.

* Implement the required `BIDSLayout` parameters through the config so that it can still be used with a snakemake workflow
  * Parameters: `database_path`, `reset_database` (am I missing any other ones?) 
* Make it backwards compatible (e.g. config without those parameters)
* Default behaviour should not overwrite the existing sqlite db

**Comment by kaitj** [comment]
Functionality to be added in #133, pending review. Would probably be good to also include this in the documentation.
