### ISSUE TITLE
`snakebids create` issues compendium

### ISSUE THREAD

**Issue by pvandyken** [akhanf/snakebids#187]
## The problem

Was just running `snakebids create` for the first time. I have some comments that I thought I'd compile here:

- [x] The command currently doesn't take any args, most glaringly the path to the directory the app should be made in. I think it's fine to "infer" this the way the wizard currently does if no path is provided, but it should still take a path
- [x] All of the fields are defaulting to @akhanf 's personal information!
- [x] The default `run.py` file gets the `snakemake_dir` wrong (it should be one parent higher)
- [ ] It would be nice to be able to leave fields blank... Not sure if cookiecutter supports this directly, but probably it's just a matter of setting defaults to blank strings.

**Comment by tkkuehn** [comment]
For that specific case, it gets used to fill out the following snippet in the docs template:

```
Install from github with pip::

    pip install -e git+https://github.com/{{cookiecutter.github_username}}/{{cookiecutter.app_name}}#egg={{cookiecutter.app_name}}
```

It's debatable whether including this level of detail in the template is even desirable (and it will be wrong if the repo gets deployed to an organization). The template prompt should certainly explain what it's for in this case, or the case could be removed, but allowing a blank here will cause the generated docs to be wrong in a way that's not obvious at a glance. I agree with your blind form filling hesitance and think the UX here needs improvement, but I don't think defaulting to blank is the best option here.

**Comment by tkkuehn** [comment]
I'll add that I can envision something like intelligently allowing blanks by defining optional fields that nix parts of the template if they're not defined. That strikes me as maybe hard to implement but would also be a nice solution.

**Comment by kaitj** [comment]
> I'll add that I can envision something like intelligently allowing blanks by defining optional fields that nix parts of the template if they're not defined. That strikes me as maybe hard to implement but would also be a nice solution.

+1 - this would be nice to have. One approach (although more naive and I haven't given it too much thought), would be to read the file after it has been created and remove any lines that are "blank". Alternatively, and this would require more digging and testing, but if I am reading the documentation correctly, Cookiecutter uses Jinja for templating. It might be possible to take advantage of this to query each key/val pair with a loop, removing lines where values are blank or `None` to the output file? This may end up being something that should be implemented in Cookiecutter rather than through Snakebids.

> Poetry does a really nice thing with the username/email where they query git to get the defaults. 

The `github_username` looks like it was part of the documentation example for Cookiecutter - I guess this might be how they differentiated for github vs gitlab vs bitbucket support. Not sure of the internals, but I presume Poetry is querying the github api with the email to grab the login (e.g. could query with my email to grab my username: https://api.github.com/search/users?q=tkai@uwo.ca)? Is this something we can query and pass through to the Cookiecutter api under `admin.py`? I agree with both about whether this is mandatory, as well as how to address the issue if this is a organizational repo rather than a user-specific repo.

**Comment by pvandyken** [comment]
> Not sure of the internals, but I presume Poetry is querying the github api with the email to grab the login (e.g. could query with my email to grab my username: https://api.github.com/search/users?q=tkai@uwo.ca)?

Nothing that complicated. It just sets the default for your Name and Email (e.g. "Peter Van Dyken <pvandyk2@uwo.ca>") by basically calling `git config user`

**Comment by kaitj** [comment]
Ahh, I assumed it was doing something more complicated. Makes sense.

**Comment by akhanf** [comment]
Yeah the github username is just what almost all cookie cutter templates use, that's where it came from. The original intent of the template was to provide users our suggestions for best practices in terms of deployment, docs etc.. I agree a power user/experienced developer may want to do their own thing, but I think having some pre-made actions etc are useful for the targeted neuroimaging researcher, but only if the instructions for setup are documented and straightforward.

I wonder if a github template repository might actually be the best way to implement the more bare-bones snakebids app? That wouldn't have any jinja templating, but would be somewhat easier for initiating a new app (ie can be done on the web instead of locally with snakebids installed already).

**Comment by pvandyken** [comment]
Since most of the issues here are resolved, I'm going to move the one remaining point to a stand-alone issue and close this
