### ISSUE TITLE
how to access the layout of a dataset?

### ISSUE THREAD

**Issue by Remi-Gau** [akhanf/snakebids#223]
I have a bids apps that requires to get some "stats" about the dataset as a whole (on top of accessing some specific files).

Is there a way that snakebids "exposes" the layout so I can access it in script or should I just create a script that will reindex the dataset with pybids?

**Comment by pvandyken** [comment]
Not yet, but this has come up before and should be low-hanging fruit. We can definitely prioritize this.

I think a reasonable API would be to just have a `BidsDataset.layout` property that points to the underlying layout object (trying to think of this will have any incompatibilities with future filtering apis, but I can't come up with anything).

**Comment by Remi-Gau** [comment]
Thanks. For now I can still reindex the dataset but it will become a pain for large datasets.

**Comment by akhanf** [comment]
Note that another workaround right now would be to use the --pybidsdb-dir option in snakebids to avoid re-indexing, and always use the same path to the pybidsdb directory (e.g. `<bids_dir>/.pybids`), so that your script can also be hardcoded to look in the same location (e.g. `<bids_dir>/.pybids`).

We also have this useful tool for generating the pybids db dir on a network file system (https://github.com/pvandyken/pybidsdb)

**Comment by pvandyken** [comment]
I'm actually facing a bit of an implementation detail on this, having to do with the types and the fact that, in testing, the fake `Datasets` I'm making will not have an associated `layout`.

There's two approaches to this: one is an `Optional` type annotation:

```py
class BidsDataset:
    layout: Optional[BIDSLayout] = None
```

I don't care for this because in practice, any `BidsDataset` generated by `generate_inputs()` will indeed have a `layout`, so from the user perspective, `layout` is not really optional.

The other is to have two classes

```py
class AbstractBidsDataset:
   ...

class BidsDataset(AbstractBidsDataset):
    layout: BIDSLayout
```

I'm planning on going with this approach: the implementation is invisible to the user and it solves the dilemma from the first. `AbstractBidsDataset` would be used in tests.
