### ISSUE TITLE
dataset_description.json generation

### ISSUE THREAD

**Issue by pvandyken** [akhanf/snakebids#54]
I would imagine the commonest use-case of this library is to generate a new derivative dataset from an existing BIDS dataset. BIDS requires a `dataset_descriptions.json` to be valid, and it would be handy if snakebids could handle this automatically. I noticed a previous commit #9 that seemed to handle this, but the code no longer seems to be present. Was there an issue in getting the implementation working correctly, or am I just missing the feature? If it is present, it doesn't seem to be documented

**Comment by akhanf** [comment]
I think that feature should still be there, it is now in the cookiecutter template that is [here](https://github.com/akhanf/snakebids/blob/main/snakebids/project_template/%7B%7Bcookiecutter.app_name%7D%7D/%7B%7Bcookiecutter.app_name%7D%7D/pipeline_description.json).

But yes we should add this to documentation if it isn't there

**Comment by pvandyken** [comment]
I think this is what's causing my confusion: https://snakebids.readthedocs.io/en/main/bids_app/workflow.html
>```
> import snakebids
>from snakebids import bids
>
>configfile: 'config/snakebids.yml'
>
>#writes inputs_config.yml and updates config dict
>config = snakebids.generate_inputs_config(config)
>
>#this adds constraints to the bids naming
>wildcard_constraints:  **snakebids.get_wildcard_constraints(config)
>```
In the current main branch, there is no function called generate_inputs_config(). And that seemed to be where the dataset_description code was. Has this been refactored? I can't find any similar code anymore on search.

**Comment by akhanf** [comment]
Ah yes you're right, the code to copy in the .json file isn't there anymore, was left out when refactoring `generate_inputs_config()` into `generate_inputs()`.. 

I am thinking it got left out because it didn't quite fit in with what generate_inputs() does or returns (ie just returning the configuration dictionary). I am thinking it may be better add this functionality into `run_snakemake()` in `app.py` instead, since that is where the updated config is written, what do you think?

**Comment by pvandyken** [comment]
Yes, that makes a lot of sense. I'll look into the old code, see if it can be put back in relatively easily, and make a PR.
